### ISSUE TITLE
camera to video

### ISSUE THREAD

**Issue by evolzed** [evolzed/armlogic#64]

**Comment by evolzed** [comment]
In light of recent work at home needs, additional function is required to take frames from videos as input to image process

**Comment by xiaobiky123** [comment]
camera to video解决方案：
       创建一个接口类imageCapture，该类和camera类具有相同的方法和返回值，在使用中用它来替换camera类即可。可以在main的初始化函数中构造该类的对象 来定制使用相机还是使用视频，从而让原来的图像处理和CNN识别代码无需更改
