### ISSUE TITLE
src/track

### ISSUE THREAD

**Issue by evolzed** [evolzed/armlogic#65]
Merged from branch 47-src-track

**Comment by evolzed** [comment]
Objective:
Get 

Requirements:

Estimate Time:

**Comment by demoivrelu** [comment]
1.Define trackProcess in Track Class, multiprocess( trackProcess& vision_run ) run in process; 
2.Information details get in trackProcess & transfer the details to other functions like cerateTarget, updatetarget...

**Comment by demoivrelu** [comment]
1.
2.跟踪到的target ，本身的框图大小尺寸不再变化；

**Comment by demoivrelu** [comment]
1. trackProcess() modified, in the end of loop, value of location & velocity is given by transList; (d8d2704e5a392c9dd2961f200c86c9c395a4119f)
2. Some bugs:at the first of createTarget(), the list("target") in targetDict could not get value from transList in every ProcessRun;
3. bottleAngle not got yet

**Comment by demoivrelu** [comment]
- [ ] 1.Judge the correlation positions in trackProcess() with that in vision_run();

**Comment by demoivrelu** [comment]
20200213 with imgProc.detectObj() & imgproc.detectObjNotRelyCnn():
 **with imgproc.detectObj:**

**Comment by demoivrelu** [comment]
1. The judgement of detcetObj (trackFlag) maybe given by the targetMove;

**Comment by demoivrelu** [comment]
Camera is OK in imageInit() and imageRun(); Test the trackProcess() with camera, One targetPoint is tracked;
