### ISSUE TITLE
src/imgProc

### ISSUE THREAD

**Issue by evolzed** [evolzed/armlogic#67]
Merged from branch 48-src-imgproc

**Comment by evolzed** [comment]
Objective:
Get video stream from camera, do simple image process and output to Track

Parameter:
- [ ] Input:
- [ ] Output:

Requirements:
- [ ] 1.
- [ ] 2.
- [ ] 3.
- [ ] 4.

Estimate Time:

**Comment by xiaobiky123** [comment]
完成 共1天

**Comment by xiaobiky123** [comment]
再做imageTrack 通过ImageProcess来detect目标，不再通过CNN

**Comment by xiaobiky123** [comment]
首先添加一个detectObjNotRelyCnn函数，该函数不通过CNN来detect目标，只通过背景学习后的图像处理来检测目标

**Comment by xiaobiky123** [comment]
增加了detectObjNotRelyCnn函数 以及filterBgBox函数不依赖神经网络 去跟踪 并将vision中的main里的detectObj替换掉 不依赖神经网络的跟踪已经调试好，会跟踪画面中的目标，面积过于小不可能是目标的不会跟踪

**Comment by xiaobiky123** [comment]
解决光斑的问题，光斑的信息也需要录入到dict中，查看bottledict 和 datadict 和centerlist

**Comment by xiaobiky123** [comment]
整理imgProc 拆分的更清楚些

**Comment by xiaobiky123** [comment]
将imgProc类拆分为三个模块，BgLearn 和 ImgTrack 和ImgTool，并调试vision通过，让程序结构更加清晰

**Comment by xiaobiky123** [comment]
2020——3——5
发现跟踪的FLAG 一直开着，detect的flag关掉，不进行detect以后，跟踪会出错
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\video\src\lkpyramid.cpp:1250: error: (-215:Assertion failed) (npoints = prevPtsMat.checkVector(2, CV_32F, true)) >= 0 in function 'cv::`anonymous-namespace'::SparsePyrLKOpticalFlowImpl::calc'
原因是flag=1 让一开始没瓶子也进入了lktrack得到的p0可能不对,但是去掉触发flag=0也不对
