### ISSUE TITLE
src/yolo

### ISSUE THREAD

**Issue by evolzed** [evolzed/armlogic#69]
Merged from branch 57-src-yolo

**Comment by evolzed** [comment]
Objective:
Get video from Vision, do Yolo

Parameter:
- [ ] Input:
- [ ] Output:

Requirements:
- [ ] 1.
- [ ] 2.
- [ ] 3.
- [ ] 4.

Estimate Time:

**Comment by yuantao1880** [comment]
进行图片贴合时，使用cv2.seamlessClone方法进行无缝拼接，没有达到预期效果。然后更换PIL库中的im.paste，发现使用PIL库时 ，保存的是透明背景瓶子图片，但在进行贴合时，发现背景无法消除。

**Comment by yuantao1880** [comment]
![bottle_01](https://user-images.githubusercontent.com/48791623/74134069-d4be5b00-4c24-11ea-9b85-a8d624b3efd1.png)
![result](https://user-images.githubusercontent.com/48791623/74134085-de47c300-4c24-11ea-8c75-1e74f446a962.jpg)
![image](https://user-images.githubusercontent.com/48791623/74134116-eef83900-4c24-11ea-8153-b356bc821c6d.png)

**Comment by yuantao1880** [comment]
瓶子旋转贴合背景完成，标注框自动生成。目前只简单贴合一种类型的瓶子，后面继续完善更复杂的功能。

**Comment by yuantao1880** [comment]
![Uploading 0c0d7049acbbb29fd6da84edb24b786.png…]()
![fdbe9bb59d6f4be8781c0ec5505096c](https://user-images.githubusercontent.com/48791623/74232176-3228d980-4d03-11ea-9a3c-543a0b6858e7.png)
![Uploading 54327b8f60b415a087c5b7b857e46f7.png…]()

**Comment by yuantao1880** [comment]
今天完成1号和2号瓶子的数据以及标注生成。预计晚上可以训练，训练完看手动贴合照片的训练效果

**Comment by yuantao1880** [comment]
自动生成图片功能完善，开始进行数据生成；
①、目前使用类别编号为0（程序自动标注）、1（贴合数据）、2（贴合数据）每个类别540张。
②、每个类别3个特征，每个特征旋转360°，每两度取一次位姿。
③、使用1620张照片，使用gtx1050Ti显卡进行训练
截至目前的训练日志如下：
Using TensorFlow backend.
2020-02-12 14:28:35.624675: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-02-12 14:28:36.624374: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1212] Found device 0 with properties:
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2020-02-12 14:28:36.633339: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1312] Adding visible gpu devices: 0
2020-02-12 14:28:38.292258: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3032 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Create Tiny YOLOv3 model with 6 anchors and 22 classes.
Train on 1458 samples, val on 162 samples, with batch size 16.
Epoch 1/50
2020-02-12 14:28:50.027309: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.22GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
91/91 [==============================] - 175s 2s/step - loss: 320.5081 - val_loss: 61.4862
Epoch 2/50
91/91 [==============================] - 158s 2s/step - loss: 32.1190 - val_loss: 28.7175
Epoch 3/50
91/91 [==============================] - 170s 2s/step - loss: 20.4674 - val_loss: 19.6869
Epoch 4/50
91/91 [==============================] - 172s 2s/step - loss: 15.4080 - val_loss: 16.1074
Epoch 5/50
91/91 [==============================] - 170s 2s/step - loss: 13.0208 - val_loss: 13.6129
Epoch 6/50
91/91 [==============================] - 161s 2s/step - loss: 11.3945 - val_loss: 10.5924
Epoch 7/50
91/91 [==============================] - 163s 2s/step - loss: 10.1172 - val_loss: 9.9183
Epoch 8/50
91/91 [==============================] - 161s 2s/step - loss: 9.5787 - val_loss: 9.2061
Epoch 9/50
91/91 [==============================] - 162s 2s/step - loss: 8.8216 - val_loss: 8.5977
Epoch 10/50
91/91 [==============================] - 164s 2s/step - loss: 8.2985 - val_loss: 9.2103
Epoch 11/50
91/91 [==============================] - 165s 2s/step - loss: 7.9942 - val_loss: 7.7708
Epoch 12/50
91/91 [==============================] - 161s 2s/step - loss: 7.7781 - val_loss: 7.4569
Epoch 13/50
91/91 [==============================] - 159s 2s/step - loss: 7.4923 - val_loss: 9.6865
Epoch 14/50
91/91 [==============================] - 157s 2s/step - loss: 7.3256 - val_loss: 8.1843
Epoch 15/50
91/91 [==============================] - 157s 2s/step - loss: 7.0653 - val_loss: 8.2962
Epoch 16/50
91/91 [==============================] - 155s 2s/step - loss: 7.0214 - val_loss: 6.9051
Epoch 17/50
91/91 [==============================] - 194s 2s/step - loss: 6.8761 - val_loss: 7.0691
Epoch 18/50
91/91 [==============================] - 164s 2s/step - loss: 6.7471 - val_loss: 8.4255
Epoch 19/50
91/91 [==============================] - 156s 2s/step - loss: 6.5750 - val_loss: 6.6255
Epoch 20/50
91/91 [==============================] - 156s 2s/step - loss: 6.5669 - val_loss: 6.8852
Epoch 21/50
91/91 [==============================] - 166s 2s/step - loss: 6.4762 - val_loss: 7.7504
Epoch 22/50
91/91 [==============================] - 159s 2s/step - loss: 6.4141 - val_loss: 6.2916
Epoch 23/50
91/91 [==============================] - 158s 2s/step - loss: 6.4242 - val_loss: 6.4023
Epoch 24/50
91/91 [==============================] - 158s 2s/step - loss: 6.1138 - val_loss: 6.5606
Epoch 25/50
91/91 [==============================] - 156s 2s/step - loss: 5.9679 - val_loss: 7.3249
Epoch 26/50
91/91 [==============================] - 164s 2s/step - loss: 6.2113 - val_loss: 6.5381
Epoch 27/50
91/91 [==============================] - 157s 2s/step - loss: 5.9877 - val_loss: 6.4200
Epoch 28/50
91/91 [==============================] - 156s 2s/step - loss: 5.9256 - val_loss: 6.0156
Epoch 29/50
91/91 [==============================] - 155s 2s/step - loss: 5.9378 - val_loss: 9.2645
Epoch 30/50
91/91 [==============================] - 156s 2s/step - loss: 5.7910 - val_loss: 7.2707
Epoch 31/50
91/91 [==============================] - 158s 2s/step - loss: 5.9125 - val_loss: 6.3945
Epoch 32/50
91/91 [==============================] - 167s 2s/step - loss: 5.5746 - val_loss: 5.3718
Epoch 33/50
91/91 [==============================] - 157s 2s/step - loss: 5.6350 - val_loss: 5.9010
Epoch 34/50
91/91 [==============================] - 154s 2s/step - loss: 5.5375 - val_loss: 5.7193
Epoch 35/50
91/91 [==============================] - 156s 2s/step - loss: 5.5845 - val_loss: 6.0165
Epoch 36/50
91/91 [==============================] - 163s 2s/step - loss: 5.5226 - val_loss: 5.4429
Epoch 37/50
91/91 [==============================] - 160s 2s/step - loss: 5.4405 - val_loss: 5.5226
Epoch 38/50
91/91 [==============================] - 163s 2s/step - loss: 5.4535 - val_loss: 6.1955
Epoch 39/50
91/91 [==============================] - 157s 2s/step - loss: 5.5312 - val_loss: 5.9791
Epoch 40/50
91/91 [==============================] - 156s 2s/step - loss: 5.3038 - val_loss: 6.8898
Epoch 41/50
91/91 [==============================] - 154s 2s/step - loss: 5.2963 - val_loss: 7.9681
Epoch 42/50
91/91 [==============================] - 158s 2s/step - loss: 5.2871 - val_loss: 5.8788
Epoch 43/50
91/91 [==============================] - 145s 2s/step - loss: 5.2382 - val_loss: 9.1188
Epoch 44/50
91/91 [==============================] - 156s 2s/step - loss: 5.3245 - val_loss: 5.7430
Epoch 45/50
91/91 [==============================] - 152s 2s/step - loss: 5.3179 - val_loss: 5.1704
Epoch 46/50
91/91 [==============================] - 150s 2s/step - loss: 5.1457 - val_loss: 5.9121
Epoch 47/50
91/91 [==============================] - 152s 2s/step - loss: 5.1782 - val_loss: 5.6040
Epoch 48/50
91/91 [==============================] - 152s 2s/step - loss: 5.0613 - val_loss: 5.4923
Epoch 49/50
91/91 [==============================] - 154s 2s/step - loss: 5.2569 - val_loss: 5.4966
Epoch 50/50
91/91 [==============================] - 158s 2s/step - loss: 5.1653 - val_loss: 5.2508
Unfreeze all of the layers.
Train on 1458 samples, val on 162 samples, with batch size 16.
Epoch 51/100
91/91 [==============================] - 166s 2s/step - loss: 4.5540 - val_loss: 4.3017
Epoch 52/100
91/91 [==============================] - 151s 2s/step - loss: 4.3422 - val_loss: 4.7144
Epoch 53/100
91/91 [==============================] - 152s 2s/step - loss: 4.3680 - val_loss: 4.7412
Epoch 54/100
91/91 [==============================] - 151s 2s/step - loss: 4.3090 - val_loss: 4.5199
Epoch 55/100
91/91 [==============================] - 149s 2s/step - loss: 4.3774 - val_loss: 4.4872

Epoch 00055: ReduceLROnPlateau reducing learning rate to 9.999999747378752e-06.
Epoch 56/100
91/91 [==============================] - 153s 2s/step - loss: 4.1484 - val_loss: 3.9160
Epoch 57/100
91/91 [==============================] - 153s 2s/step - loss: 4.1422 - val_loss: 3.9465
Epoch 58/100
91/91 [==============================] - 156s 2s/step - loss: 4.1090 - val_loss: 3.9769
Epoch 59/100
91/91 [==============================] - 152s 2s/step - loss: 4.0199 - val_loss: 4.4265
Epoch 60/100
91/91 [==============================] - 150s 2s/step - loss: 4.0154 - val_loss: 3.9181

Epoch 00060: ReduceLROnPlateau reducing learning rate to 9.999999747378752e-07.
Epoch 61/100
91/91 [==============================] - 149s 2s/step - loss: 4.0056 - val_loss: 4.0785
Epoch 62/100
91/91 [==============================] - 149s 2s/step - loss: 4.0172 - val_loss: 3.8492
Epoch 63/100
91/91 [==============================] - 149s 2s/step - loss: 4.0925 - val_loss: 4.2340
Epoch 64/100
91/91 [==============================] - 148s 2s/step - loss: 4.0123 - val_loss: 4.0430
Epoch 65/100
91/91 [==============================] - 146s 2s/step - loss: 4.0170 - val_loss: 4.2241
Epoch 66/100
91/91 [==============================] - 149s 2s/step - loss: 3.9982 - val_loss: 4.1536

Epoch 00066: ReduceLROnPlateau reducing learning rate to 9.999999974752428e-08.
Epoch 67/100
91/91 [==============================] - 149s 2s/step - loss: 4.0821 - val_loss: 4.0707
Epoch 68/100
91/91 [==============================] - 152s 2s/step - loss: 3.9780 - val_loss: 4.1044
Epoch 69/100
91/91 [==============================] - 149s 2s/step - loss: 4.1256 - val_loss: 4.4337

Epoch 00069: ReduceLROnPlateau reducing learning rate to 1.0000000116860975e-08.
Epoch 70/100
91/91 [==============================] - 149s 2s/step - loss: 4.0149 - val_loss: 3.9044

**Comment by yuantao1880** [comment]
虽然模型训练和验证的loss不错，也能很快收敛，但其中也有不少问题：

其中的问题：
①、对2号偏白的瓶子识别效果不错。但对于1号类别，识别不如2号类别
②、对1号瓶子泛化能力不是很理想。考虑是不是贴合中处理的bottle的外界扰动性大。
③、多个物体在一起时，框比较大，把多个物体全部框进去了

可能的原因：
①、2号白色标签的瓶子，虽然时人工合成的数据，但效果明显较好。对于物体颜色和背景高对比度的物体，比较容易训练。但合成所采用的1号类别，选用比较不错的素材最好的也比较暗（年前那一批数据是晚上采集的数据）
②、如果瓶身透明一点的话，皮带的颜色干扰比较大，会加重图像中物体的颜色深度（更暗），皮带对于非透明的瓶身影响不大

对应策略：
①、从光线、素材等方面。还有多物体一起重叠问题数据的构造（主要是物体重叠时的标注框自动生成问题）
②、谨慎选取干扰不大的瓶子素材进行合成数据

**Comment by yuantao1880** [comment]
发现模型损失函数能够快速下降，因为，贴合的数据，边缘比较锐利，对图像边缘使用羽化处理，另外对背景和bottle物体，增加了随机伽马光线处理。以使得模型对光线的泛化能力更强

**Comment by yuantao1880** [comment]
查阅资料和文献，寻找并尝试把模型的泛化能力提高，争取拿真正整合的数据来运用到实际生产中使用

**Comment by yuantao1880** [comment]
记录改变适当的亮度的训练结果。亮度调整一定要合适，bg（0.6-1.5），bottle（0.5-1.2）
![40189dfce3bbc6b77edb88037ba1e32](https://user-images.githubusercontent.com/48791623/74506838-aa76e100-4f35-11ea-8005-d4bc3ebbebff.png)
![Uploading ba9d06f9a2e871f05f1952131925615.png…]()

**Comment by yuantao1880** [comment]
对于相对复杂些的场景依然可以识别
![image](https://user-images.githubusercontent.com/48791623/74507893-b021f600-4f38-11ea-8bb9-cf5886f15730.png)

**Comment by yuantao1880** [comment]
根据今日训练结果。发现，背景太单一，可能是导致泛化能力一直不好的主要原因，结合imgAug官方文档，利用晚上时间。对背景进行随机增强处理，然后再进行贴合。但出现了一个小bug，一直没解决掉。代码已提交【2020-0214-23:27】

**Comment by yuantao1880** [comment]
修bug，并增加了背景旋转的概率：大致效果如下
![image](https://user-images.githubusercontent.com/48791623/74546040-e1c0ae80-4f84-11ea-935b-79b0ded5b8ae.png)

**Comment by yuantao1880** [comment]
训练模型。查看一个编号1的训练效果

**Comment by yuantao1880** [comment]
简单进行epochs的训练过程以及效果：
![0d5032851585a20d5dcaa71ac888d35](https://user-images.githubusercontent.com/48791623/74580642-545f7780-4fe1-11ea-9ccb-932145f46e6a.png)



Using TensorFlow backend.
2020-02-15 09:28:11.950553: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-02-15 09:28:12.933303: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1212] Found device 0 with properties:
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2020-02-15 09:28:12.947337: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1312] Adding visible gpu devices: 0
2020-02-15 09:28:13.963493: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3032 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Create Tiny YOLOv3 model with 6 anchors and 22 classes.
Train on 900 samples, val on 100 samples, with batch size 16.
Epoch 1/20
2020-02-15 09:28:24.944877: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.22GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
56/56 [==============================] - 94s 2s/step - loss: 431.2333 - val_loss: 108.6378
Epoch 2/20
56/56 [==============================] - 87s 2s/step - loss: 42.8720 - val_loss: 49.2605
Epoch 3/20
56/56 [==============================] - 95s 2s/step - loss: 26.8057 - val_loss: 31.9226
Epoch 4/20
56/56 [==============================] - 96s 2s/step - loss: 20.6147 - val_loss: 23.7920
Epoch 5/20
56/56 [==============================] - 96s 2s/step - loss: 18.1689 - val_loss: 18.8972
Epoch 6/20
56/56 [==============================] - 102s 2s/step - loss: 16.0711 - val_loss: 16.7684
Epoch 7/20
56/56 [==============================] - 96s 2s/step - loss: 14.7349 - val_loss: 17.0653
Epoch 8/20
56/56 [==============================] - 96s 2s/step - loss: 13.7403 - val_loss: 13.8995
Epoch 9/20
56/56 [==============================] - 94s 2s/step - loss: 13.1985 - val_loss: 13.0719
Epoch 10/20
56/56 [==============================] - 98s 2s/step - loss: 12.2406 - val_loss: 12.6332
Epoch 11/20
56/56 [==============================] - 101s 2s/step - loss: 11.8884 - val_loss: 14.5514
Epoch 12/20
56/56 [==============================] - 100s 2s/step - loss: 11.4189 - val_loss: 12.9342
Epoch 13/20
56/56 [==============================] - 101s 2s/step - loss: 10.9226 - val_loss: 13.1119
Epoch 14/20
56/56 [==============================] - 100s 2s/step - loss: 10.6159 - val_loss: 11.5166
Epoch 15/20
56/56 [==============================] - 100s 2s/step - loss: 10.0822 - val_loss: 11.5259
Epoch 16/20
56/56 [==============================] - 102s 2s/step - loss: 9.7066 - val_loss: 10.0347
Epoch 17/20
56/56 [==============================] - 97s 2s/step - loss: 9.5966 - val_loss: 9.5103
Epoch 18/20
56/56 [==============================] - 105s 2s/step - loss: 9.2696 - val_loss: 10.1187
Epoch 19/20
56/56 [==============================] - 104s 2s/step - loss: 9.2315 - val_loss: 11.4801
Epoch 20/20
56/56 [==============================] - 104s 2s/step - loss: 9.1372 - val_loss: 9.1385
Unfreeze all of the layers.
Train on 900 samples, val on 100 samples, with batch size 16.
Epoch 21/30
56/56 [==============================] - 117s 2s/step - loss: 8.5006 - val_loss: 8.4757
Epoch 22/30
56/56 [==============================] - 105s 2s/step - loss: 8.2889 - val_loss: 8.4644
Epoch 23/30
56/56 [==============================] - 101s 2s/step - loss: 8.0485 - val_loss: 8.4262
Epoch 24/30
56/56 [==============================] - 99s 2s/step - loss: 7.5742 - val_loss: 8.3886
Epoch 25/30
56/56 [==============================] - 101s 2s/step - loss: 7.6819 - val_loss: 7.8117
Epoch 26/30
56/56 [==============================] - 105s 2s/step - loss: 7.4724 - val_loss: 7.0200
Epoch 27/30
56/56 [==============================] - 106s 2s/step - loss: 7.3675 - val_loss: 7.7674
Epoch 28/30
56/56 [==============================] - 104s 2s/step - loss: 7.2506 - val_loss: 6.9014
Epoch 29/30
56/56 [==============================] - 97s 2s/step - loss: 7.1397 - val_loss: 7.2910
Epoch 30/30
56/56 [==============================] - 93s 2s/step - loss: 7.1482 - val_loss: 7.7302

**Comment by yuantao1880** [comment]
开始困难样本（相似度高的种类）的训练研究

**Comment by yuantao1880** [comment]
分别制作类别为2、3、9、18、19号瓶子图片
![image](https://user-images.githubusercontent.com/48791623/74658848-16737680-51ce-11ea-9dc3-640f26572148.png)

**Comment by yuantao1880** [comment]
遇到一个问题，多个瓶子随机散落在背景中，如果瓶子之间有遮挡（覆盖），瓶子的位置标注信息将发生很大变化，目前的解决思路有两个：
1、让瓶子半随机散落，避免瓶子之间有重叠和覆盖的情况。
2、判断瓶子之间的覆盖面积，设置阈值，如果覆盖超过阈值再舍弃。这样可能会有利于处理小部分覆盖或者遮挡的情况

**Comment by yuantao1880** [comment]
先用无目标瓶子的背景作为背景，生成数据集，训练看效果，为后面的训练提供参考依据

**Comment by yuantao1880** [comment]
5types，5000pics。train logs：

Using TensorFlow backend.
2020-02-18 10:55:01.638501: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-02-18 10:55:02.608506: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1212] Found device 0 with properties:
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2020-02-18 10:55:02.616441: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1312] Adding visible gpu devices: 0
2020-02-18 10:55:03.709008: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3032 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Create Tiny YOLOv3 model with 6 anchors and 22 classes.
Train on 4500 samples, val on 500 samples, with batch size 16.
Epoch 1/20
2020-02-18 10:55:14.778140: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.22GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
281/281 [==============================] - 531s 2s/step - loss: 108.8363 - val_loss: 19.4988
Epoch 2/20
281/281 [==============================] - 449s 2s/step - loss: 14.6509 - val_loss: 13.2411
Epoch 3/20
281/281 [==============================] - 441s 2s/step - loss: 11.7691 - val_loss: 12.5875
Epoch 4/20
281/281 [==============================] - 440s 2s/step - loss: 10.6468 - val_loss: 11.0640
Epoch 5/20
281/281 [==============================] - 441s 2s/step - loss: 9.4074 - val_loss: 9.0314
Epoch 6/20
281/281 [==============================] - 439s 2s/step - loss: 8.6228 - val_loss: 8.8121
Epoch 7/20
281/281 [==============================] - 439s 2s/step - loss: 8.0837 - val_loss: 8.5264
Epoch 8/20
281/281 [==============================] - 451s 2s/step - loss: 7.6841 - val_loss: 7.7712
Epoch 9/20
281/281 [==============================] - 463s 2s/step - loss: 7.2704 - val_loss: 7.8210
Epoch 10/20
281/281 [==============================] - 448s 2s/step - loss: 7.0258 - val_loss: 7.7130
Epoch 11/20
281/281 [==============================] - 462s 2s/step - loss: 6.7479 - val_loss: 6.6586
Epoch 12/20
281/281 [==============================] - 464s 2s/step - loss: 6.6293 - val_loss: 6.8936
Epoch 13/20
281/281 [==============================] - 458s 2s/step - loss: 6.3436 - val_loss: 6.6972
Epoch 14/20
281/281 [==============================] - 446s 2s/step - loss: 6.2283 - val_loss: 7.6296
Epoch 15/20
281/281 [==============================] - 446s 2s/step - loss: 6.1086 - val_loss: 5.8380
Epoch 16/20
281/281 [==============================] - 446s 2s/step - loss: 5.8851 - val_loss: 6.0950
Epoch 17/20
281/281 [==============================] - 446s 2s/step - loss: 5.8695 - val_loss: 5.6285
Epoch 18/20
281/281 [==============================] - 447s 2s/step - loss: 5.6849 - val_loss: 5.8289
Epoch 19/20
281/281 [==============================] - 447s 2s/step - loss: 5.7638 - val_loss: 5.9573
Epoch 20/20
281/281 [==============================] - 445s 2s/step - loss: 5.5957 - val_loss: 5.6956
Unfreeze all of the layers.
Train on 4500 samples, val on 500 samples, with batch size 16.
Epoch 21/30
281/281 [==============================] - 464s 2s/step - loss: 4.9175 - val_loss: 4.8236
Epoch 22/30
281/281 [==============================] - 449s 2s/step - loss: 4.7551 - val_loss: 4.6410
Epoch 23/30
281/281 [==============================] - 448s 2s/step - loss: 4.6199 - val_loss: 4.5262
Epoch 24/30
281/281 [==============================] - 449s 2s/step - loss: 4.5726 - val_loss: 4.5316
Epoch 25/30
281/281 [==============================] - 447s 2s/step - loss: 4.4317 - val_loss: 4.5670
Epoch 26/30
281/281 [==============================] - 447s 2s/step - loss: 4.3950 - val_loss: 4.4461
Epoch 27/30
281/281 [==============================] - 448s 2s/step - loss: 4.4040 - val_loss: 4.5024
Epoch 28/30
281/281 [==============================] - 449s 2s/step - loss: 4.3355 - val_loss: 4.1729
Epoch 29/30
281/281 [==============================] - 448s 2s/step - loss: 4.2672 - val_loss: 4.3223
Epoch 30/30
281/281 [==============================] - 448s 2s/step - loss: 4.2218 - val_loss: 4.3197

**Comment by yuantao1880** [comment]
困难样本的训练效果
![image](https://user-images.githubusercontent.com/48791623/74737855-a8dc4e80-5290-11ea-9704-3ba73dc1d5eb.png)

**Comment by yuantao1880** [comment]
昨天训练出现的问题：
①、对于相靠太近的物体，识别不太好
②、一个物体，框的位置一样，但会给出两个不同概率不同类别的标签
因为，我们不能采用多个类别绝对不干扰的方式，需要利用不同物体中的贴合IOU进行筛选

**Comment by yuantao1880** [comment]
计算生成图片IOU算法原理实现。【2020-0219-23:05】
![image](https://user-images.githubusercontent.com/48791623/74846809-16a97880-536c-11ea-88f8-b57b9a534938.png)

**Comment by yuantao1880** [comment]
Today，将算法应用到图片生成中，找出比较合适的iou设置参数，用来生成比较合适的多物体数据集

**Comment by yuantao1880** [comment]
Iou计算完善完毕，但整和到之前的数据生成中，截止到目前2020-0220-2300，还未修改完毕。预计还要大半天时间。

**Comment by yuantao1880** [comment]
模拟的优化效果展示：
![image](https://user-images.githubusercontent.com/48791623/74947043-39539400-5435-11ea-9bed-f3208a1a08a4.png)

**Comment by yuantao1880** [comment]
继续编写多物体同时生成到一张背景下

**Comment by yuantao1880** [comment]
多物体随机生成在背景图中，已完成。简单效果展示：
![image](https://user-images.githubusercontent.com/48791623/75021304-1d043580-54cf-11ea-9882-88e3de07dd99.png)
![image](https://user-images.githubusercontent.com/48791623/75021319-24c3da00-54cf-11ea-8930-aee0d25ae4e1.png)

**Comment by yuantao1880** [comment]
修复背景裁剪后黑色区域的处理以及背景无法进行gama亮度随机变换的bug

**Comment by yuantao1880** [comment]
每种瓶子暂采集8个位姿，然后随机进行数据生成

**Comment by yuantao1880** [comment]
修复部分bug，利用现有的处理过的瓶子生成4000张照片，进行训练：
![image](https://user-images.githubusercontent.com/48791623/75139815-8df25a00-5728-11ea-8ecc-77e92fb08e7a.png)

**Comment by yuantao1880** [comment]
利用现有6类4000张图片进行的简单训练效果：
![image](https://user-images.githubusercontent.com/48791623/75158826-eb4ed100-5751-11ea-8ab8-4dfc2c963c63.png)
![image](https://user-images.githubusercontent.com/48791623/75158866-f99ced00-5751-11ea-96c0-d42e9c39d753.png)

**Comment by yuantao1880** [comment]
继续制作单个瓶子的数据采集。但多物体同时生成的情况下，需要排除掉之前瓶身不完整的数据

**Comment by yuantao1880** [comment]
制作了0、8、11、12、13、14、16、17、20号瓶的部分bottle数据

**Comment by yuantao1880** [comment]
利用程序生成的数据集进行训练，采用1w张，其中5000张是切分出来的原始数据，另外5000张是对背景和前景分别进行过颜色通道转换之后的数据。训练loss：68。测试集表现良好，但对于视频的处理出现问题。视频中会将检测结果集中在8号瓶上。
测试集结果：
![image](https://user-images.githubusercontent.com/48791623/76043849-a453ad80-5f93-11ea-9d24-8612bf690133.png)
视频中结果：
![image](https://user-images.githubusercontent.com/48791623/76043977-f563a180-5f93-11ea-84c4-70afa474b541.png)

**Comment by yuantao1880** [comment]
YoloV3-tiny使用总结：
数据集方向：
①证实了程序生成的数据集以及自动标注的可实施性。
②对于困难样本的训练也可以使用数据增强的方法进行处理。
③数据集处理过程对于通道进行转换有一定必要性。
④为了能够适应相机的角度和距离变换，对于前景应该进行一定的缩放变换
网络模型方向：
①使用yolo-tiny在gtx1050Ti和gtx980上可训练性
②yolo-tiny虽然网络有精简，但从训练的效果来看，还是比较满意。
③可以尝试增加网络层数进行优化
出现的问题：
①刚开始模型对图片识别效果不错，但对于视频的识别效果极差，由于视频帧和图片的色彩模式不同导致
②对于位置较近的困难样本识别，容易出错
可以考虑的探索方向：
①利用k-means算法，生成自己的anchors进行训练
②可以不使用yolo-tiny的预训练weights.h5进行训练

**Comment by yuantao1880** [comment]
附：效果展示
![TOOI3974](https://user-images.githubusercontent.com/48791623/76076157-3f22ab00-5fd9-11ea-84d9-4a6c74da2663.gif)
![PCFK7468](https://user-images.githubusercontent.com/48791623/76076192-52357b00-5fd9-11ea-9811-ab9c31b63d70.gif)
