### ISSUE TITLE
tracking 和 imageProcess 两个进程同步的问题

### ISSUE THREAD

**Issue by xiaobiky123** [evolzed/armlogic#72]
实现tracking 和 imageProcess 两个进程同步，从而达到两个进程区分开，才可以让imageProcess的图像分析 去修正tracking的运动估计

**Comment by demoivrelu** [comment]
如果 是p1.start()  会出现图示error；如果p1.run() 则可以跑通vision

**Comment by evolzed** [comment]
https://static.dingtalk.com/media/lALPDgQ9rhfm4O_NAoPNA4k_905_643.png_620x10000q90g.jpg?bizType=im

**Comment by demoivrelu** [comment]
![lALPDgQ9rhfm4O_NAoPNA4k_905_643](https://user-images.githubusercontent.com/35356984/73993730-0d90d280-498e-11ea-8748-ef3be9442c84.png)

**Comment by yuantao1880** [comment]
![589e39f2d6b626268a9def28f3f27c9](https://user-images.githubusercontent.com/48791623/74083312-9b0f1800-4a9d-11ea-9223-fb21fdbd8f1a.png)
![ae1fc4d141c8e518608a63e4378e773](https://user-images.githubusercontent.com/48791623/74083317-a06c6280-4a9d-11ea-8ac2-276532bf791e.png)
![8c9a7b8b6e7437ef4c9549d7f75259c](https://user-images.githubusercontent.com/48791623/74083323-ae21e800-4a9d-11ea-9921-76e3393f5d21.png)

**Comment by yuantao1880** [comment]
已解决
