### ISSUE TITLE
Tools/DDStreamWorkHour

### ISSUE THREAD

**Issue by evolzed** [evolzed/armlogic#73]
Objective:
Create new tool that will run on DDTalk client during conference stream, do simple image processing and save the results.

Parameters:
Input: DDTalk conference recording
Output1: Workhour.xml (each username, total minutes worked, each log entry)
Output2: screenshot.jpg (at random interval save screenshot with timestamp as name)

Flowchart:

- [x] 1. Input conference recording video image into DDWorkHourCal
- [x] 2. User input order of user in conference call
- [x] 3. Tool takes screenshot at random interval (0.5min ~ 2 mins)
- [x] 4. Compare with previous screenshot for difference:
          If any difference is found check the area of screen associated with user add user work hour count
- [x] 5. Roll dice to decide whether to save new screenshot. 

Requirements:
- [x] Random screenshot will be kept for longer duration for user to recall at later date.

/Estimate 1d

**Comment by xiaobiky123** [comment]
complete all the function,now test and improve it 
/spend 1d

**Comment by xiaobiky123** [comment]
改成从视频里读图片 而不是从截图里

**Comment by xiaobiky123** [comment]
把ddWorkHourCal功能修改到可以使用的地步 并添加了注释 可以立刻拿来测试 添加了使用方法，界面清晰，一开始投掷骰子决定是否将每个人的截图随机时间保存，然后运行中即可实时看到每个人的时间刷新 结束后每个人的工作时间会存放在Excel表里面

**Comment by xiaobiky123** [comment]
本工具运行方法，首先设定本地保存屏幕截图的路径captureDir，设定存放钉钉录制视频的路径videoDir，设定保存标定图片的路径calibDir，设定保存工作时间表的路径excelDir，
然后运行程序，在标定图片路径下获得了标定图片，
用画图软件打开这张图片，看左上角点的坐标，填写在left,top上，看一个格子的宽度和高度，填写在
gw，gh上,关闭程序
再重新运行程序，投掷骰子，如果骰子掷为6，则随机时间保存屏幕截图，否则不保存，观察运行窗口，
实时查看每个人的工作时间显示在左上角，小数位数较多，每分钟会更新一次
工作结束按q退出,会保存每个人的工作时间在excel表中，excel表的文件名已经加上时间戳

**Comment by xiaobiky123** [comment]
存在这样一个问题，大家在视频会议中不能离开，如果离开再进来 九宫格的顺序就会改变，计算时间就会错误，想到的解决方法是识别每个格子左下角的名字，来确定该格子是谁的格子

**Comment by xiaobiky123** [comment]
今天测试这个软件 按照上午和下午

**Comment by xiaobiky123** [comment]
1.中午吃饭休息时间 12点到1点 ，涛涛提出中午晚下班但是中午会议已经关闭，怎么计时，这个可以个人提出中午多做了多少时间，在代码中给一个接口，增加上中午做事的工时。

**Comment by xiaobiky123** [comment]
计算屏幕变化的间隔以0.5--2分钟有些少，考虑到大家的思考时间，改成5--10分钟

**Comment by xiaobiky123** [comment]
发现一个bug 录像完毕后 不会正常退出 导致excel 没有得到保存 需要录像完毕的判断，现在开始修复

**Comment by xiaobiky123** [comment]
再一个问题 就是统计的时间有些少 今天查明原因 看看是不是间隔的问题

**Comment by xiaobiky123** [comment]
发现统计时间少的原因在哪里了，原因在于抽帧间隔 大于视频本身的帧 间隔，就是抽帧频率低，导致一个4小时的视频，两个小时不到就抽完了，所以导致算出来的时间都低，需要重新研究 camera 用视频代替的接口问题

**Comment by xiaobiky123** [comment]
修改了video接口，增加了视频总时间属性和视频帧间隔属性，并用来解决统计时间少的问题，就是将原先的时间加上帧间隔时间再减去自主延时的时间，就计算出了准确的工作时间，目前等视频跑完看结果，按照这种方法，用两个小时即可对4个小时的视频做出工作时间的统计

**Comment by xiaobiky123** [comment]
刚的修正还存在问题，经分析，视频时间的补偿的计算方式还是不对，现在对video 和interface 增加了获取视频的当前时刻接口，由此计算出了每次统计工作时间时 真正的视频流逝时间，从而完全修正了工作时间的统计，经过测试，正确！

**Comment by xiaobiky123** [comment]
现在又发现新的问题，就是发现统计的时间偏长，这是由于没有减去算法执行的时间，导致的不确定性误差，尝试优化

**Comment by xiaobiky123** [comment]
时间已经修复正确，现在解决格子顺序的问题，现在已经完成了 KNN 算法来进行数字识别的调试验证，上传代码后，会应用到 区分哪个格子是哪个人上面

**Comment by xiaobiky123** [comment]
增加了通过mnist数据集和KNN算法来识别数字图片中的数字功能，增加了Mnist,KNN模块，并调试通过，可以准确识别1，2，3，5四个数字，将用于实现区分不同格子

**Comment by xiaobiky123** [comment]
优化了阈值，现在除了6，7，9 三个数字识别不出来，其余7个数字都可以识别出来

**Comment by xiaobiky123** [comment]
把数字识别集成到了 工作时间统计上，粗定位右下角的数字，然后形态学分析细致定位到数字框出来，然后调用KNN识别数字，为了抽取视频中的图像，顺带给视频模块增加了，抽取任意时刻的画面功能，相当于快进和 暂停

**Comment by xiaobiky123** [comment]
将数字识别整合进了ddworkHour,数字和人名关联了起来，不害怕格子顺序的改变，是谁的工时就加到谁的工时上面，不再会错了，要求就是大家都要把数字号显示在自己窗口右下角

**Comment by xiaobiky123** [comment]
KNN算法数字识别的速度过慢，运行起来比较卡顿，识别有一定的出错几率，为了提高数字识别的速度和准确度，改用pytorch构建两层全连接网络来识别数字

**Comment by xiaobiky123** [comment]
全连接网络实验成功，识别数字准确率和速度得到很大的提升

**Comment by xiaobiky123** [comment]
全连接网络识别数字已经整合到时间检测系统中 速度和准确率都得到了极大的提升 现在反而数字图形的定位不太稳定 容易受每个人摆放位置的影响

**Comment by xiaobiky123** [comment]
修正了没有0的key的bug 和之前的一个bug 现在已经完全实用，但是存在的问题，就是每次都要适配数字的位置，需要升级数字的定位算法

**Comment by xiaobiky123** [comment]
编写了若干常用小功能块儿，如excel，时间戳，显示，前后帧处理框架等等，方便随时使用和移植

**Comment by xiaobiky123** [comment]
增加了倍速功能 测试10倍速得出的统计时间是正确的 当然数字识别还存在问题，这样一个小时的视频，6分钟即可分析完毕，同时增加了视频接口的设定帧功能，增加了视频总时间的logo, 定位算法持续开发中，

**Comment by xiaobiky123** [comment]
统计完了2月24号的工作时间，上传至网盘https://pan.baidu.com/disk/home?#/all?vmode=list&path=%2F%E6%8A%80%E6%9C%AF%E9%83%A8%2F%E5%9C%A8%E7%BA%BF%E5%8A%9E%E5%85%AC%2F%E6%AF%8F%E5%A4%A9%E7%9A%84%E5%B7%A5%E4%BD%9C%E6%97%B6%E9%97%B4%E5%92%8C%E5%BD%95%E5%83%8F%E5%AF%B9%E7%85%A7   视频和表对照

**Comment by evolzed** [comment]
> 统计完了2月24号的工作时间，上传至网盘https://pan.baidu.com/disk/home?#/all?vmode=list&path=%2F%E6%8A%80%E6%9C%AF%E9%83%A8%2F%E5%9C%A8%E7%BA%BF%E5%8A%9E%E5%85%AC%2F%E6%AF%8F%E5%A4%A9%E7%9A%84%E5%B7%A5%E4%BD%9C%E6%97%B6%E9%97%B4%E5%92%8C%E5%BD%95%E5%83%8F%E5%AF%B9%E7%85%A7 视频和表对照

视频及结果储存在那个文件夹里？

**Comment by xiaobiky123** [comment]
今日测试发现问题：定位准确度不高，数字图片的大小不均，加边框的多少，也会导致识别出错

**Comment by xiaobiky123** [comment]
通过分析原因，解决了上述问题，通过加边框辅助解决了定位不准的问题，修正了图片二值化后和灰度图格式不一致导致无法识别的问题，增强了全连接网络的参数，提高了准确度，现在准确率大大提升，但是也发现全连接网络对于位置和形变十分敏感，增加边界也会改变识别结果

**Comment by xiaobiky123** [comment]
现在能够进行工时统计，但是容易出问题，结果就是拿到数字2的人的工时是准确的，现在给了小鲁，其他数字容易串，效果就是参加会议并且工作的工时会少算一些，但不参加会议的基本没有工时，主要原因是由于数字图片的定位不准确，希望在空余时间慢慢通过SSD训练来改进73ef58d6fb2d7a07f6ff8dd16866481b950712af
