### ISSUE TITLE
PC Work

### ISSUE THREAD

**Issue by evolzed** [evolzed/armlogic#78]
SSR科学上网
 - [x] Monthly subscription
 - [x] Auto connect on PC

/estimate 1d

**Comment by evolzed** [comment]
GitLab / GitHub
- [ ] sync Branch
- [ ] sync Issue
- [ ] Remote connection onto GitLab

**Comment by evolzed** [comment]
DingDing video conference

- [ ] Install DingDing client on PC
- [ ] Setup 24 hour recording of video conference
- [ ] Run DDWorkHour.exe
- [ ] Save recording data and results in folder location: (to be determined)

**Comment by Caspar-cao** [comment]
老胡脚本还无法正常运行，有执行上的问题。远程控制问题已经解决。

**Comment by evolzed** [comment]
> DingDing video conference
> 
> * [x]  Install DingDing client on PC
> * [x]  Setup 24 hour recording of video conference
> * [x]  Run DDWorkHour.exe
> * [x]  Save recording data and results in folder location: (to be determined)

功能完成后再打勾！

**Comment by Caspar-cao** [comment]
SSR科学上网解决步骤
1.购买SSR的上网节点
2.通过购买的刷过老毛子固件的路由器设置SSR的订阅号
3.调试订阅号的网络节点

DingDing video conference
1.由于钉钉ubuntu版本只是一个阉割版本，无法实现正常的视频通话，所以采用ubuntu安装vmware虚拟机配置一个windows系统，来进行会议建立
2.通过远程工具向日葵解决在家远程操控的问题。
3.DDWorkHour.exe运行上还是有一定的问题，交给老胡进行修复，暂时视频记录通过老胡进行处理。
4.已建立存放目录

/estimate 3d
