### ISSUE TITLE
数据存储规范——百度网盘

### ISSUE THREAD

**Issue by initial-heart** [evolzed/armlogic#79]
神经网络训练数据统一存放到公司百度网盘“技术部/Image/Data”路径下；

Data文件夹结构如图所示：

![Untitled Diagram](https://user-images.githubusercontent.com/39988460/75332472-6681c580-58bf-11ea-839d-ed79f4072a14.jpg)

#### Data目录

存放所有采集到的数据，规则如下：

* XSCX用于存放在办公室采集的图片，HangZhou存放在杭州市采集的数据，“ ... ”表示其它地区的目录，使用规则同上。
* 另外若没有对应采集地的目录，则创建相应地点的文件夹。
* 采集后未标注的数据，全部放于相应地点的根目录中，例如在办公室采集的未标注的数据，直接存放在XSCX目录下。在标注后将其移入到Processed目录中，并且对应的标注信息上传到Annotation 目录中

每个地区目录中都需包含以下子目录：Annotation、Background、Foreground、Processed、Simuation，各目录功能如下表所示

| 文件夹     | 介绍                           |
| ---------- | ------------------------------ |
| Annotation | 存放数据的标注文件             |
| Background | 存放杭州市采集的数据           |
| Foreground | 存放用于合成数据时使用的前景图 |
| Processed  | 存放已经标注过的数据           |
| Simuation  | 存放通过程序合成的数据         |

**Comment by initial-heart** [comment]
将百度网盘data目录进行了整理，根据采集存储规范对数据进行规范化，并将数据上传到百度网盘指定位置

**Comment by initial-heart** [comment]
已按新规则对数据全部进行了整理
XSCX目录已创建，HangZhou目录因没有数据暂时未进行创建
![Data](https://user-images.githubusercontent.com/39988460/75333841-cc6f4c80-58c1-11ea-9996-0368687bab2d.jpg)
对应的各二级目录已完成创建
![XSCX](https://user-images.githubusercontent.com/39988460/75333954-fd4f8180-58c1-11ea-9ccd-2545f69cbeb8.jpg)
二级目录Annotation中的数据已进行上传
![Annotation](https://user-images.githubusercontent.com/39988460/75334099-3b4ca580-58c2-11ea-8977-933681e9e7bb.jpg)
二级目录Background中的数据已进行上传
![Background](https://user-images.githubusercontent.com/39988460/75334181-59b2a100-58c2-11ea-819e-3d5b258e9d90.jpg)
二级目录Foreground中的数据已进行上传
![Foreground](https://user-images.githubusercontent.com/39988460/75334324-97172e80-58c2-11ea-98e9-8cf30a980fad.jpg)
二级目录Processed中的数据已进行上传
![Processed](https://user-images.githubusercontent.com/39988460/75334332-9a121f00-58c2-11ea-9bca-84c0a3f75e3d.jpg)
二级目录Simuation中的数据已进行上传
![Simuation](https://user-images.githubusercontent.com/39988460/75334336-9c747900-58c2-11ea-93a9-331f4dbde6da.jpg)

**Comment by evolzed** [comment]
Completed

**Comment by zhiming6** [comment]
* 在Data/XSCX/ForegroundImage文件夹中添加子文件夹：4号雪碧(绿)，5号雪碧(白绿)，6号脉动，10号娃哈哈，11号怡宝，12号雀巢咖啡，15号东方树叶，16号茉莉清茶，20号每益添。
* Data/XSCX/ForegroundImage/0号农夫山泉文件夹里添加照片数据17张。
* Data/XSCX/ForegroundImage/1号可口可乐文件夹里添加照片数据16张。
* Data/XSCX/ForegroundImage/2号雪碧(白)文件夹里添加照片数据11张。
* Data/XSCX/ForegroundImage/3号元汽水文件夹里添加照片数据12张。
* Data/XSCX/ForegroundImage/4号雪碧(绿)文件夹里添加照片数据14张。
* Data/XSCX/ForegroundImage/5号雪碧(白绿)文件夹里添加照片数据20张。
* Data/XSCX/ForegroundImage/6号脉动文件夹里添加照片数据20张。
* Data/XSCX/ForegroundImage/7号百岁山文件夹里添加照片数据19张。
* Data/XSCX/ForegroundImage/8号海之言文件夹里添加照片数据17张。
* Data/XSCX/ForegroundImage/9号纯享文件夹里添加照片数据2张。
* Data/XSCX/ForegroundImage/10号娃哈哈文件夹里添加照片数据11张。
* Data/XSCX/ForegroundImage/11号怡宝文件夹里添加照片数据17张。
* Data/XSCX/ForegroundImage/12号雀巢咖啡文件夹里添加照片数据11张。
* Data/XSCX/ForegroundImage/13号椰汁文件夹里添加照片数据15张。
* Data/XSCX/ForegroundImage/14号拿铁文件夹里添加照片数据10张。
* Data/XSCX/ForegroundImage/15号东方树叶文件夹里添加照片数据20张。
* Data/XSCX/ForegroundImage/16号茉莉清茶文件夹里添加照片数据14张。
* Data/XSCX/ForegroundImage/17号可口可乐(680ml)文件夹里添加照片数据16张。
* Data/XSCX/ForegroundImage/18号蒙牛酸奶文件夹里添加照片数据8张。
* Data/XSCX/ForegroundImage/19号初心文件夹里添加照片数据10张。
* Data/XSCX/ForegroundImage/20号每益添文件夹里添加照片数据14张。
* Data/XSCX/ForegroundImage/21号激活文件夹里添加照片数据21张。
