### ISSUE TITLE
Data process procedure

### ISSUE THREAD

**Issue by evolzed** [evolzed/armlogic#81]
- [x] Data process flowchart
- [x] Issue Template
- [x] Template Translate into Chinese
- [x] Pull Request Template
- [x] CNN function flowchart

/estimate 3d

**Comment by initial-heart** [comment]
数据处理流程图：
![issuesFlowchart](https://user-images.githubusercontent.com/39988460/75542995-df1d8900-5a5b-11ea-8a13-a883904a5895.png)
issues template:
![issues](https://user-images.githubusercontent.com/39988460/75543007-e2b11000-5a5b-11ea-91db-7567fc010bee.png)
pull request template:
![pull](https://user-images.githubusercontent.com/39988460/75543016-e6dd2d80-5a5b-11ea-9e4e-c9a5d3fe65a9.png)

**Comment by evolzed** [comment]
> ### 数据处理流程图：
> ![issuesFlowchart](https://user-images.githubusercontent.com/39988460/75542995-df1d8900-5a5b-11ea-8a13-a883904a5895.png)
> 
提供ProcessOn的链接

**Comment by initial-heart** [comment]
ProcessOn链接：http://www.processon.com/collaboration/invite/5e59c5e3e4b0541c5e132cdf

**Comment by initial-heart** [comment]
CNN function flowchart
![flowchart](https://user-images.githubusercontent.com/39988460/75618637-2fa3fc00-5bac-11ea-997a-23c5e463d564.jpg)
