### ISSUE TITLE
tools/DataProcess.py

### ISSUE THREAD

**Issue by evolzed** [evolzed/armlogic#90]
清楚而简明地描述问题是什么。例如：当……时我总是很沮丧。
大量文件需要进行重命名，手动操作耗时费力

**Describe the solution you'd like**
**描述你想要的解决方案**
输入文件目录等信息，对输入目录下的文件进行重命名，重命名完成后进行自动标注和目标提取，将标注信息以Json格式保存到Annotation目录，提取到的目标存储到Foreground目录，背景存储到Background目录

**Comment by initial-heart** [comment]
设计流程图：
![设计流程图](https://user-images.githubusercontent.com/39988460/75739344-9b6a9e00-5d3f-11ea-91be-d8fb020df0ac.jpg)

**Comment by initial-heart** [comment]
**测试需求**：

1. 初始化信息是否被记录

2. 文件打开是否正常

3. 数据经过网络后是否进行了标注

4. 错误标注的数据是否可被标记

5. 标注信息是否被正确存储

6. 图像数据是否被正确存储

7. 所有要处理的数据是否被依次遍历

**Comment by evolzed** [comment]
- [ ] 编写代码

/estimate 2d

**Comment by initial-heart** [comment]
结果显示需处理一张显示一张，如果想全部处理完毕再显示，需要修改已有的yolo.py文件，可能会和涛涛产生冲突 @evolzed
