### ISSUE TITLE
[Test] System run time 运行时间测试：

### ISSUE THREAD

**Issue by evolzed** [evolzed/armlogic#98]
运行时间测试：
- [ ]

@xiaobiky123

_Originally posted by @evolzed in https://github.com/evolzed/armlogic/issues/80#issuecomment-594996453_

**Comment by xiaobiky123** [comment]
把CNN,背景学习的算法时间都整合起来，形成一个统一接口

**Comment by evolzed** [comment]
> 把CNN,背景学习的算法时间都整合起来，形成一个统一接口

/estimate 1d

**Comment by xiaobiky123** [comment]
的通用接口，是一个类，使用起来简单方便，已经用它计算出了背景学习，跟踪，yoLo的时间，为图像跟踪检测修复了一个瓶子无法检测更多的问题，并为图像跟踪修复了一个跟踪点清空的bug，并开始观察跟踪结束后图像的跟踪点变化，找出跟踪失败或结束时的标志  /spend 3h

**Comment by xiaobiky123** [comment]
经过计算 各算法消耗时间如下
BgLearnTime = 23.590800 ms
YoloTime = 64.029500 ms
LkTrackTime = 5.287000 ms

**Comment by xiaobiky123** [comment]
2020/3/6
今天 优化bgLearn的时间 /estimate 3h

**Comment by xiaobiky123** [comment]
优化了bglearn的时间，由平均25毫秒 优化成了平均18毫秒

**Comment by xiaobiky123** [comment]
增加了对detect的时间测试，平均30ms，但detect是每秒钟调用一次，后续考虑和神经网络一起，每秒钟调用一次
