### ISSUE TITLE
[Data] 网盘上的图像数据转移到GitLab上

### ISSUE THREAD

**Issue by evolzed** [evolzed/armlogic#99]
![Untitled Diagram](https://user-images.githubusercontent.com/39988460/75511927-bc26b100-5a2a-11ea-9eec-1581f3c42fcd.jpg)
---
 
进行数据处理时，请按以下顺序进行
- [x] 数据重命名
  * 命名格式为日期时间编号(时间精确到秒)
- [x] 标注数据
  * 根据任务需求完成相应的标注任务，标注信息以Json格式进行存储
- [x] 更新说明文档
  * 说明文字直接追加到已有的说明文档最后，应包含以下信息
    * 数据范围：所标注数据的起始文件名和终止文件名
    * 标注数量：总的标注图片数
    * 标注时间：开始时间和结束时间或者只填结束时间
    * 标注人员：多个人员用英文逗号隔开
    * 标注工具：标注软件名，若用代码合成，则填写函数名
    * 备注：上述信息外的额外内容
- [x] 上传标注数据
  * 将标注文件上传到Annotation目录中
- [x] 上传重命名后的数据到相应目录
  * 按照给定规则对标注数据进行重命名，并在标注完成后，将重命名的数据上传到Processed目录中

请勾选上述已完成项目,并在该Issues中回复数据范围、标注数量、标注时间、标注人员、标注工具、备注等信息

**Comment by zhiming6** [comment]
网盘上的图像数据已转移到GitLab上，在文件夹数据数量超过1000的一律新建多个子文件夹来分别存放。
![Exhibition](https://user-images.githubusercontent.com/51504057/76067519-776ebd00-5fca-11ea-8107-83eee306b8bc.png)

**Comment by evolzed** [comment]
> 网盘上的图像数据已转移到GitLab上，在数据数量超过1000的文件夹一律新建多个子文件夹来分别存放。
> ![Exhibition](https://user-images.githubusercontent.com/51504057/76067921-2c08de80-5fcb-11ea-93dc-3af51d68ad1b.png)

请提供1000张一个的子文件夹截图

**Comment by zhiming6** [comment]
文件夹里子文件夹截图和子文件夹所含部分内容截图展示。
![2020-03-06 183308](https://user-images.githubusercontent.com/51504057/76076216-5d88a680-5fd9-11ea-9197-ab795dfa7dff.png)
![2020-03-06 183406](https://user-images.githubusercontent.com/51504057/76076223-637e8780-5fd9-11ea-8704-fc07034183c6.png)
